In [1]:
import pandas as pd

test_df = pd.read_csv('../data/Antai_AE_round1_test_20190626.csv')
print(test_df.shape[0])
test_df.head()

166832

  buyer_country_id  buyer_admin_id   item_id    create_order_time  irank
0               yy         1061132    189045  2018-07-17 07:43:40     18
1               yy         1081430  10713670  2018-07-17 09:43:15      8
2               yy         1918135  10546322  2018-07-17 11:11:34      9
3               yy          103277   5199603  2018-07-17 13:27:44     24
4               yy          103277   2477273  2018-07-17 13:27:44     22

In [2]:
import zipfile

# 默认模式r,读
train_zip = zipfile.ZipFile('../data/Antai_AE_round1_train_20190626.zip')
item_zip = zipfile.ZipFile('../data/Antai_AE_round1_item_attr_20190626.zip') 
print(train_zip.namelist())
print(item_zip.namelist())
train = train_zip.open('Antai_AE_round1_train_20190626.csv')
item = item_zip.open('Antai_AE_round1_item_attr_20190626.csv')

import pandas as pd
train_df = pd.read_csv(train)
train_df.head()

['Antai_AE_round1_train_20190626.csv']
['Antai_AE_round1_item_attr_20190626.csv']

  buyer_country_id  buyer_admin_id  item_id    create_order_time  irank
0               xx         8362078        1  2018-08-10 23:49:44     12
1               xx         9694304        2  2018-08-03 23:55:07      9
2               yy          101887        3  2018-08-27 08:31:26      3
3               xx         8131786        3  2018-08-31 06:00:19      9
4               xx         9778613        5  2018-08-21 06:01:56     14

In [3]:
item_df = pd.read_csv(item)
item_df.head()

   item_id  cate_id  store_id  item_price
0   240607     1495     12239           1
1   285232     1498     12239           1
2   113669     1503     12239           1
3   253601     1422     12239           1
4   246568     1497     12239           1

In [4]:
train_yy = train_df[train_df['buyer_country_id']=='yy']
train_yy.head()

   buyer_country_id  buyer_admin_id  item_id    create_order_time  irank
2                yy          101887        3  2018-08-27 08:31:26      3
9                yy          288460        6  2018-08-31 13:41:25     11
10               yy          341958        6  2018-08-31 15:42:10      1
12               yy        12849617        6  2018-08-09 04:10:36     17
16               yy          770888        6  2018-08-31 23:33:54     12

In [53]:
train_yy.shape[0]

860192

In [57]:
train_yy.drop_duplicates('buyer_admin_id').shape[0]

128931

# 热销品

In [9]:
hot_item_10 = pd.DataFrame(pd.concat([test_df,train_yy]).groupby(['item_id']).size(),columns=['cnt']).sort_values('cnt',ascending=False)[:10]
hot_item_10

           cnt
item_id
11717821  1505
11140901  1492
5595070   1378
11680535  1337
2850195   1295
3227771   1290
10389160  1275
10617258  1095
3866632   1090
10788165  1035

# 历史购买

In [10]:
tmp = test_df[test_df['irank']<=31].sort_values(by=['buyer_country_id','buyer_admin_id','irank'])[['buyer_admin_id','item_id','irank']]

In [12]:
tmp.head()

       buyer_admin_id  item_id  irank
91354             152  8410857      2
91357             152  7937154      3
91352             152  8472223      4
91356             152  4016066      5
91353             152  9891513      6

In [43]:
tmp.set_index(['buyer_admin_id','irank']).unstack(-1)

                   item_id                                                  \
irank                   2           3           4           5           6
buyer_admin_id
152              8410857.0   7937154.0   8472223.0   4016066.0   9891513.0
282             11721802.0   7665423.0   7665423.0  10808393.0  11310708.0
321              1461800.0   7379845.0   9243286.0   7379845.0    627849.0
809              2347616.0   5707010.0   6339286.0   5492003.0   1207574.0
870             11382694.0   5999244.0   6611583.0   7412272.0   4343647.0
2410             1991652.0   3010258.0   8734237.0   5529566.0  12328639.0
2956             7116759.0   7116759.0   8778275.0   5039457.0   5071633.0
3866             3738221.0   8326767.0   3366910.0   3366910.0   9638971.0
7277            11977450.0   8343022.0  10813894.0  11826481.0    465594.0
7944            10039927.0  11659460.0   7598016.0   9607731.0   9555054.0
8192             1306627.0   4538161.0   9715746.0   4538161.0   6857974.0
8408             9988978.0   4244544.0    665393.0   1195177.0   1192063.0
8464               70466.0   2914396.0   2914396.0   2686621.0   2094230.0
8637             5639030.0   8910564.0   5703905.0   7334003.0   8693860.0
8760             5813336.0   8940662.0  11075083.0   5813336.0   4184067.0
9015             3703072.0   2775264.0     18284.0    924117.0   1222930.0
9035             5831736.0   1527698.0   7432186.0   7432186.0   8260171.0
9079              153030.0   7886311.0   2203597.0   4376203.0   2341287.0
10146            1239063.0   1239063.0   1239063.0  11493702.0  11493702.0
10836            4218750.0     59243.0   4945981.0    764094.0    336653.0
11092            6017984.0   8057645.0   2969882.0   8545184.0    519838.0
12072            1434548.0  10318396.0   3261925.0   6029609.0   5145720.0
13571            2368260.0    488153.0   6680629.0    450460.0    488153.0
13851            2583077.0    188395.0    188395.0   2089807.0   1926597.0
14685            3625865.0   9765458.0   2476527.0   1927238.0   4691607.0
14757            2563363.0   6268181.0   1474959.0   8460299.0   1040334.0
15114            2466013.0   7064738.0   7063375.0  12407710.0   4173879.0
15195            9916576.0  10069486.0  11426762.0  11557841.0    979922.0
17068            7386561.0  12101505.0  11341806.0  11948261.0   4578167.0
17141           10424369.0   2211474.0   5137224.0    807187.0    807187.0
...                    ...         ...         ...         ...         ...
13008196        11422157.0   8820011.0  11422157.0  11422157.0  11422157.0
13024265         5820727.0  12303807.0  11730821.0   7806166.0   3920932.0
13024323         9958307.0  10224561.0   5285377.0  11078733.0    508272.0
13024369        10677730.0   8225052.0   9885717.0   9885717.0  10130173.0
13025072         2241981.0   7829553.0  11528914.0  10161164.0  10161164.0
13025986         7548364.0   7548364.0  11716597.0  10252830.0   5739415.0
13026568         6195597.0   6195597.0   6195597.0   6195597.0   6195597.0
13027356         7550184.0   9478701.0   7027025.0  12631443.0   9478701.0
13027430         5181424.0   2822821.0    862201.0   5867257.0   2822821.0
13028759         2092745.0  11198066.0   3612060.0   2006166.0    669545.0
13028937         6408695.0   3092992.0   1509553.0   6278237.0   6278237.0
13028976         9326463.0   5516858.0   1982301.0   5857431.0   1290259.0
13029399         8547587.0   8547587.0   8547587.0   8547587.0   8547587.0
13029522        10047489.0   7642328.0  12915569.0   1948215.0   5738940.0
13029742         4629356.0   6462197.0   2236345.0   1006260.0   5650268.0
13029924        10952271.0   4886901.0  11672262.0  11977196.0   1563814.0
13029976         3121849.0   3121849.0    347955.0   3121849.0   2989407.0
13030926         2742001.0   6677984.0   6677984.0   2742001.0   5056744.0
13032038         6455563.0   1042927.0    779820.0   3760021.0   6495186.0
13034116         1422506.0   9507238.0   4597001.0   1750657.0  10815434.0
13035742         2766726.0   2766726.0   2766726.0   2766726.0   2766726.0
13037285         5311193.0   4424159.0   3619538.0   4160229.0  11216403.0
13037296         6586041.0   8457004.0   8755974.0   8457004.0   8755974.0
13038422        10622510.0  10622510.0  10622510.0  10622510.0  10622510.0
13039625         6199491.0   6371563.0   6371563.0   6371563.0    335237.0
13041046         4465563.0   4433564.0   6466730.0    173060.0    173140.0
13041581         7168968.0   9669996.0   9669996.0  10159313.0   7027641.0
13044048         9052525.0  11680535.0  11680535.0     63066.0   2447752.0
13046354        10391871.0   7945295.0   7100322.0   9556217.0   9776214.0
13046601         5619538.0   5619538.0   5619538.0   5619538.0   5619538.0

                                                                            \
irank                   7           8           9           10          11
buyer_admin_id
152              8064216.0   8351840.0         NaN         NaN         NaN
282               623582.0   6547607.0   2605373.0    688799.0    623582.0
321              5000759.0  11774753.0  10932288.0   4813286.0   9816501.0
809              5707010.0   5492003.0   1207574.0   2262443.0         NaN
870              5546383.0   3432696.0   9589237.0   6163411.0   8952725.0
2410             3010258.0   8829154.0  11536411.0   6594315.0  12182628.0
2956             9105860.0   1866761.0   7644819.0   1284838.0    745619.0
3866            12222697.0  12222697.0   9796213.0  10241163.0   6240908.0
7277            11550594.0   2354126.0  12543036.0  11977450.0  12226234.0
7944             4280956.0   9089404.0   6884658.0   6795431.0   4280956.0
8192             9846407.0   3132866.0    250407.0   9631903.0   2972034.0
8408              665359.0  13035792.0   4502347.0  10242192.0         NaN
8464             4157502.0   2076583.0   4157502.0   2093281.0   4589918.0
8637            11359278.0    251404.0         NaN         NaN         NaN
8760             7195147.0  11075083.0         NaN         NaN         NaN
9015             6268272.0   5300682.0         NaN         NaN         NaN
9035             2307115.0   1414382.0         NaN         NaN         NaN
9079             3964013.0   1274512.0   4403361.0  11733620.0   4229747.0
10146            1239063.0   1239063.0   3261925.0   5139229.0  10832838.0
10836            8094014.0   5162355.0    988711.0   5320360.0   1402358.0
11092            9802330.0   7580109.0   6452394.0    426384.0   9041374.0
12072            8297580.0  11290885.0   9485505.0         NaN         NaN
13571             495494.0   1741609.0         NaN         NaN         NaN
13851            1917001.0   1913880.0   2085920.0         NaN         NaN
14685            9888588.0   1874005.0         NaN         NaN         NaN
14757            4528851.0     25436.0   3475210.0   8869549.0         NaN
15114            7145390.0   6188539.0  10922386.0  10354543.0  10659439.0
15195            8768039.0   3335895.0   3991030.0   3216850.0   7826134.0
17068            4790754.0   5728775.0   4018668.0  10283527.0   1748774.0
17141            8889646.0   8889646.0   9354704.0    196193.0   4696797.0
...                    ...         ...         ...         ...         ...
13008196        11422157.0  10692087.0   8117410.0  11422157.0         NaN
13024265         7720538.0   9861363.0   8517264.0    766240.0   2733142.0
13024323          508272.0    508272.0         NaN         NaN         NaN
13024369         3312405.0  11708409.0  11708409.0  11708409.0  11708409.0
13025072         7650488.0   3025084.0   9352298.0   2256656.0   9688536.0
13025986         9520867.0   2885471.0   7173733.0         NaN         NaN
13026568         6195597.0   6195597.0   8948627.0   1889299.0         NaN
13027356        12474522.0   7027025.0   6071521.0   8856789.0  11745725.0
13027430           61817.0    228559.0  11277872.0  10664121.0   1666832.0
13028759         6418543.0  11550263.0  11585585.0  10462842.0  10462842.0
13028937         7805265.0   2744603.0         NaN         NaN         NaN
13028976        10602651.0   4852733.0  10602651.0   8777086.0   6504380.0
13029399         8547587.0   8547587.0   8547587.0   8547587.0   8547587.0
13029522         9711211.0   4350575.0   1948215.0   4350575.0  10426966.0
13029742         1205870.0  11857149.0   3500888.0   8768979.0  10468169.0
13029924         5823501.0   4886901.0   8421677.0  12999448.0  11739293.0
13029976          347955.0   3121849.0   2488092.0   1222225.0    941515.0
13030926         9014194.0  10126333.0   6677984.0    945275.0   9014194.0
13032038         3903709.0  10121545.0   9520329.0   8433918.0   7984550.0
13034116        10782889.0   5017824.0   4597001.0   2368605.0   4597001.0
13035742         2766726.0   2766726.0         NaN         NaN         NaN
13037285         4708788.0   5338822.0   6281579.0   4424159.0   4048876.0
13037296         8755974.0   6121134.0   6586041.0   8457004.0   6586041.0
13038422        10622510.0  10622510.0  10622510.0  10622510.0  10622510.0
13039625         9009201.0   6662644.0   4522369.0   6662644.0   2643626.0
13041046         4987070.0  10811396.0  11922313.0  12379158.0  10226388.0
13041581         5447793.0   5447793.0   6491935.0   6491935.0   9845944.0
13044048        11680535.0  11124939.0   9052525.0         NaN         NaN
13046354        12400852.0  12569394.0         NaN         NaN         NaN
13046601         5619538.0   5619538.0   5619538.0   5619538.0   5619538.0

                ...                                                  \
irank           ...          22          23          24          25
buyer_admin_id  ...
152             ...         NaN         NaN         NaN         NaN
282             ...         NaN         NaN         NaN         NaN
321             ...         NaN         NaN         NaN         NaN
809             ...         NaN         NaN         NaN         NaN
870             ...         NaN         NaN         NaN         NaN
2410            ...  11573165.0   3475210.0   2843593.0    904577.0
2956            ...         NaN         NaN         NaN         NaN
3866            ...   4428979.0   2275245.0   6600260.0  12553122.0
7277            ...         NaN         NaN         NaN         NaN
7944            ...         NaN         NaN         NaN         NaN
8192            ...   8957171.0   6208283.0         NaN         NaN
8408            ...         NaN         NaN         NaN         NaN
8464            ...   8994530.0   8673091.0  11055796.0    115517.0
8637            ...         NaN         NaN         NaN         NaN
8760            ...         NaN         NaN         NaN         NaN
9015            ...         NaN         NaN         NaN         NaN
9035            ...         NaN         NaN         NaN         NaN
9079            ...         NaN         NaN         NaN         NaN
10146           ...         NaN         NaN         NaN         NaN
10836           ...         NaN         NaN         NaN         NaN
11092           ...         NaN         NaN         NaN         NaN
12072           ...         NaN         NaN         NaN         NaN
13571           ...         NaN         NaN         NaN         NaN
13851           ...         NaN         NaN         NaN         NaN
14685           ...         NaN         NaN         NaN         NaN
14757           ...         NaN         NaN         NaN         NaN
15114           ...         NaN         NaN         NaN         NaN
15195           ...         NaN         NaN         NaN         NaN
17068           ...         NaN         NaN         NaN         NaN
17141           ...   9811248.0   5221582.0   1155126.0         NaN
...             ...         ...         ...         ...         ...
13008196        ...         NaN         NaN         NaN         NaN
13024265        ...         NaN         NaN         NaN         NaN
13024323        ...         NaN         NaN         NaN         NaN
13024369        ...         NaN         NaN         NaN         NaN
13025072        ...         NaN         NaN         NaN         NaN
13025986        ...         NaN         NaN         NaN         NaN
13026568        ...         NaN         NaN         NaN         NaN
13027356        ...         NaN         NaN         NaN         NaN
13027430        ...         NaN         NaN         NaN         NaN
13028759        ...         NaN         NaN         NaN         NaN
13028937        ...         NaN         NaN         NaN         NaN
13028976        ...         NaN         NaN         NaN         NaN
13029399        ...         NaN         NaN         NaN         NaN
13029522        ...         NaN         NaN         NaN         NaN
13029742        ...  10400954.0   2279331.0   5175546.0   6416591.0
13029924        ...         NaN         NaN         NaN         NaN
13029976        ...         NaN         NaN         NaN         NaN
13030926        ...         NaN         NaN         NaN         NaN
13032038        ...  10645315.0         NaN         NaN         NaN
13034116        ...         NaN         NaN         NaN         NaN
13035742        ...         NaN         NaN         NaN         NaN
13037285        ...         NaN         NaN         NaN         NaN
13037296        ...         NaN         NaN         NaN         NaN
13038422        ...  10622510.0  10622510.0  10622510.0  10622510.0
13039625        ...   7249331.0   7249331.0   1221648.0   5477019.0
13041046        ...         NaN         NaN         NaN         NaN
13041581        ...         NaN         NaN         NaN         NaN
13044048        ...         NaN         NaN         NaN         NaN
13046354        ...         NaN         NaN         NaN         NaN
13046601        ...   5619538.0   5619538.0   5619538.0   5619538.0

                                                                           \
irank                   26          27          28          29         30
buyer_admin_id
152                    NaN         NaN         NaN         NaN        NaN
282                    NaN         NaN         NaN         NaN        NaN
321                    NaN         NaN         NaN         NaN        NaN
809                    NaN         NaN         NaN         NaN        NaN
870                    NaN         NaN         NaN         NaN        NaN
2410                   NaN         NaN         NaN         NaN        NaN
2956                   NaN         NaN         NaN         NaN        NaN
3866             1429449.0  12215314.0   1429449.0   1290204.0  9759810.0
7277                   NaN         NaN         NaN         NaN        NaN
7944                   NaN         NaN         NaN         NaN        NaN
8192                   NaN         NaN         NaN         NaN        NaN
8408                   NaN         NaN         NaN         NaN        NaN
8464            10322913.0  10322913.0  10322913.0   4569637.0  4569637.0
8637                   NaN         NaN         NaN         NaN        NaN
8760                   NaN         NaN         NaN         NaN        NaN
9015                   NaN         NaN         NaN         NaN        NaN
9035                   NaN         NaN         NaN         NaN        NaN
9079                   NaN         NaN         NaN         NaN        NaN
10146                  NaN         NaN         NaN         NaN        NaN
10836                  NaN         NaN         NaN         NaN        NaN
11092                  NaN         NaN         NaN         NaN        NaN
12072                  NaN         NaN         NaN         NaN        NaN
13571                  NaN         NaN         NaN         NaN        NaN
13851                  NaN         NaN         NaN         NaN        NaN
14685                  NaN         NaN         NaN         NaN        NaN
14757                  NaN         NaN         NaN         NaN        NaN
15114                  NaN         NaN         NaN         NaN        NaN
15195                  NaN         NaN         NaN         NaN        NaN
17068                  NaN         NaN         NaN         NaN        NaN
17141                  NaN         NaN         NaN         NaN        NaN
...                    ...         ...         ...         ...        ...
13008196               NaN         NaN         NaN         NaN        NaN
13024265               NaN         NaN         NaN         NaN        NaN
13024323               NaN         NaN         NaN         NaN        NaN
13024369               NaN         NaN         NaN         NaN        NaN
13025072               NaN         NaN         NaN         NaN        NaN
13025986               NaN         NaN         NaN         NaN        NaN
13026568               NaN         NaN         NaN         NaN        NaN
13027356               NaN         NaN         NaN         NaN        NaN
13027430               NaN         NaN         NaN         NaN        NaN
13028759               NaN         NaN         NaN         NaN        NaN
13028937               NaN         NaN         NaN         NaN        NaN
13028976               NaN         NaN         NaN         NaN        NaN
13029399               NaN         NaN         NaN         NaN        NaN
13029522               NaN         NaN         NaN         NaN        NaN
13029742         8672274.0   6593386.0   8696622.0  10063876.0  4752350.0
13029924               NaN         NaN         NaN         NaN        NaN
13029976               NaN         NaN         NaN         NaN        NaN
13030926               NaN         NaN         NaN         NaN        NaN
13032038               NaN         NaN         NaN         NaN        NaN
13034116               NaN         NaN         NaN         NaN        NaN
13035742               NaN         NaN         NaN         NaN        NaN
13037285               NaN         NaN         NaN         NaN        NaN
13037296               NaN         NaN         NaN         NaN        NaN
13038422        10622510.0         NaN         NaN         NaN        NaN
13039625         2643626.0   2643626.0         NaN         NaN        NaN
13041046               NaN         NaN         NaN         NaN        NaN
13041581               NaN         NaN         NaN         NaN        NaN
13044048               NaN         NaN         NaN         NaN        NaN
13046354               NaN         NaN         NaN         NaN        NaN
13046601         5619538.0   5619538.0   5619538.0   5619538.0  5619538.0


irank                  31
buyer_admin_id
152                   NaN
282                   NaN
321                   NaN
809                   NaN
870                   NaN
2410                  NaN
2956                  NaN
3866             447451.0
7277                  NaN
7944                  NaN
8192                  NaN
8408                  NaN
8464            4569637.0
8637                  NaN
8760                  NaN
9015                  NaN
9035                  NaN
9079                  NaN
10146                 NaN
10836                 NaN
11092                 NaN
12072                 NaN
13571                 NaN
13851                 NaN
14685                 NaN
14757                 NaN
15114                 NaN
15195                 NaN
17068                 NaN
17141                 NaN
...                   ...
13008196              NaN
13024265              NaN
13024323              NaN
13024369              NaN
13025072              NaN
13025986              NaN
13026568              NaN
13027356              NaN
13027430              NaN
13028759              NaN
13028937              NaN
13028976              NaN
13029399              NaN
13029522              NaN
13029742        9941150.0
13029924              NaN
13029976              NaN
13030926              NaN
13032038              NaN
13034116              NaN
13035742              NaN
13037285              NaN
13037296              NaN
13038422              NaN
13039625              NaN
13041046              NaN

In [49]:
tmp2 = pd.DataFrame(tmp.groupby(['buyer_admin_id','item_id']).size(),columns=['cnt']).sort_values('cnt',ascending=False).groupby(['buyer_admin_id']).head(10).reset_index().sort_values(['buyer_admin_id','cnt'],ascending=False)

In [50]:
tmp2.head()

       buyer_admin_id   item_id  cnt
0            13046601   5619538   30
38724        13046354  12569394    1
38725        13046354  12400852    1
38726        13046354  10391871    1
38727        13046354   9776214    1

# User Based

In [60]:
test_df_1 = test_df.groupby(['item_id']).size().reset_index().rename(columns={0:'cnt'}).sort_values(by=['cnt'],ascending=False)
test_df['item_id'] = test_df['item_id'].astype('str')
test_df_1['item_id'] = test_df_1['item_id'].astype('str')
test_df_2 = test_df[['buyer_admin_id','item_id']].groupby(['buyer_admin_id']).agg(lambda x: ' '.join(x.values))
print(test_df_2.shape[0])
test_df_2.head()

11398

                                                          item_id
buyer_admin_id
152             8351840 8472223 9891513 8410857 8064216 401606...
282             6547607 9677940 10808393 11536575 688799 11310...
321             10570664 9759248 10000188 10000188 9759248 263...
809             2347616 2262443 5492003 5707010 6339286 120757...
870             8952725 6787506 6163411 7412272 10234567 43436...

In [90]:
test_df_2

                                                          item_id
buyer_admin_id
152             8351840 8472223 9891513 8410857 8064216 401606...
282             6547607 9677940 10808393 11536575 688799 11310...
321             10570664 9759248 10000188 10000188 9759248 263...
809             2347616 2262443 5492003 5707010 6339286 120757...
870             8952725 6787506 6163411 7412272 10234567 43436...
2410            11573165 7667925 1156153 3242952 904577 115731...
2956            7535052 7358377 745619 1284838 7644819 1866761...
3866            1192286 3388420 3991184 1192286 4428949 119228...
7277            6561610 530503 5482394 6775644 12441577 123570...
7944            6884658 5680299 6795431 9089404 4280956 428095...
8192            1575758 8957171 8012537 6208283 6208283 544123...
8408            10242192 4502347 13035792 665393 665359 119517...
8464            8673145 8241688 8673145 11055796 8673091 11037...
8637            7334003 5703905 8910564 11359278 5639030 25140...
8760            11075083 7195147 4184067 5813336 11075083 8940...
9015            5300682 3703072 18284 1222930 924117 2775264 6...
9035            1414382 2307115 8260171 7432186 7432186 152769...
9079            1274512 4376203 7886311 3964013 3315312 234128...
10146           3057411 3057411 3057411 2856736 10832838 10832...
10836           5320360 988711 1402358 5162355 764094 4945981 ...
11092           9041374 426384 6452394 7580109 9802330 519838 ...
12072           9485505 11290885 8297580 5145720 6029609 32619...
13571           488153 450460 488153 495494 2368260 6680629 17...
13851           1913880 1926597 2089807 2085920 1917001 188395...
14685           1927238 1874005 4691607 9888588 9765458 247652...
14757           8869549 3475210 25436 4528851 1040334 8460299 ...
15114           3743673 6129782 6110437 10659439 10354543 1092...
15195           3216850 7826134 3335895 3991030 979922 1142676...
17068           7528585 9951478 1748774 9664704 10283527 74940...
17141           1155126 5221582 9811248 6903778 793452 1042436...
...                                                           ...
13008196        8117410 11422157 11422157 11422157 10692087 11...
13024265        1915296 2733142 766240 8517264 9861363 7720538...
13024323        508272 508272 508272 5285377 10224561 9958307 ...
13024369        11499000 7828425 7828425 13001397 13001397 130...
13025072        4286877 9688536 2256656 9352298 3025084 765048...
13025986        2885471 7173733 10252830 5739415 9520867 75483...
13026568        1889299 8948627 6195597 6195597 6195597 619559...
13027356        12474522 9478701 6071521 9478701 7027025 70270...
13027430        5867257 1666832 11277872 862201 228559 61817 1...
13028759        10462842 10462842 11585585 11550263 6418543 66...
13028937        2744603 7805265 6278237 6278237 1509553 309299...
13028976        5857431 4852733 10602651 9326463 1290259 55168...
13029399        9301834 8547587 8547587 8547587 8547587 854758...
13029522        12915569 10047489 7642328 4350575 4350575 9711...
13029742        5175546 4752350 8672274 8696622 4990485 731638...
13029924        4886901 11739293 11977196 11672262 8421677 129...
13029976        2524958 1396531 941515 941515 941515 1396531 2...
13030926        945275 10196667 9014194 9014194 2742001 274200...
13032038        10645315 8895179 7513739 8895179 11476064 1138...
13034116        4597001 6266686 10782889 1850199 1507320 50178...
13035742        2766726 2766726 2766726 2766726 2766726 276672...
13037285        5311193 4048876 4424159 4424159 3619538 628157...
13037296        8755974 8755974 6586041 6121134 8457004 845700...
13038422        10622510 10622510 10622510 10622510 10622510 1...
13039625        4522369 6662644 1221648 5477019 5477019 122164...
13041046        8463489 10226388 12379158 11922313 10811396 49...
13041581        9897075 11385307 12418021 12418021 1620994 984...
13044048        11124939 9052525 9052525 11680535 63066 116805...
13046354        12569394 9776214 9556217 12400852 7100322 7945...
13046601        5619538 5619538 5619538 5619538 5619538 561953...

[11398 rows x 1 columns]

In [61]:
train_yy_1 = train_yy.groupby(['item_id']).size().reset_index().rename(columns={0:'cnt'}).sort_values(by=['cnt'],ascending=False)
train_yy['item_id'] = train_yy['item_id'].astype('str')
train_yy_1['item_id'] = train_yy_1['item_id'].astype('str')
train_yy_1_1 = train_yy_1[train_yy_1['cnt']>=3]
train_yy = train_yy[train_yy['item_id'].isin(train_yy_1_1['item_id'])]
train_yy_2 = train_yy[['buyer_admin_id','item_id']].groupby(['buyer_admin_id']).agg(lambda x: ' '.join(x.values))
print(train_yy_2.shape[0])
train_yy_2.head()

128931

                                                          item_id
buyer_admin_id
111                                      8816044 8816044 10665523
119                                      2719441 7659205 11007197
142                      8139992 8345489 9110673 9907121 13015745
160                                               2689986 9984565
169             5793197 5793197 5793197 6456547 8122258 812225...

In [62]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
train_yy_v = vec.fit_transform(train_yy_2['item_id'])
train_yy_v

<128931x52059 sparse matrix of type '<class 'numpy.int64'>'
	with 631999 stored elements in Compressed Sparse Row format>

In [63]:
test_df_v = vec.transform(test_df_2['item_id'])
test_df_v

<11398x52059 sparse matrix of type '<class 'numpy.int64'>'
	with 47373 stored elements in Compressed Sparse Row format>

In [92]:

import numpy as np

result = []
for i in range(test_df_v.shape[0]):
    test_i = test_df_v[i]
    test_1 = train_yy_v * test_i.T
    test_1 = test_1.toarray()
    corr_mat = np.argsort(-test_1.T,axis=1)
#     print(corr_mat)
#     corr_top_lst = corr_mat[:,0:2][0]
#     print(train_xx_1.iloc[corr_top_lst,:].values)
#     print(" ".join(train_xx_1.iloc[corr_top_lst,:].values.flatten()))
    j = 1
    top_n = 0
    top_30 = 30
    item_top = []
    while top_n<top_30:
        corr_top_lst = corr_mat[:,0:j][0]
        item_lst_clue = " ".join(train_yy_2.iloc[corr_top_lst,:].values.flatten()).split(" ")
        item_lst_have = test_df.iloc[i,].values[0].split(" ")
        item_top = set(item_lst_clue) - set(item_lst_have)
        top_n = len(item_top)
        j = j+1
#         print(item_lst_clue)
#         print(item_lst_have)
#         print(top_n)
    result.append([test_df_2.iloc[i,].name] + list(item_top)[0:30])

result = pd.DataFrame(result)
result

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,152,8972418,8120958,2972303,8776384,11652776,9767549,10126350,7514606,7089267,...,2924440,9349588,10638666,10074514,10543553,4135788,12271157,8053758,1296427,10983289
1,282,587944,2763762,8775507,10451658,450648,4645442,9468405,688799,8125178,...,2471339,1798906,9148291,6437206,267049,7682888,10874983,10751353,10832806,8791661
2,321,586919,6112486,8323907,10353195,7801551,8866319,11291525,9487175,11618343,...,11806174,10409454,9121708,908415,12378539,10932288,9146333,10380965,11285079,9433020
3,809,1516143,11145130,5637308,5378133,5474676,2881693,11271996,908091,10574845,...,4730945,10554725,10250524,3107999,7714410,6098755,2759133,1941444,8286698,1207574
4,870,10234567,8221716,6283374,5457033,7288025,4736979,10102903,7453169,9109107,...,8108773,11588836,1944281,8243183,9906904,5851000,1550141,12653622,8286698,1840691
5,2410,12458910,12209047,6005085,3571658,11202399,11570008,9573932,10190220,12011589,...,11611425,7354085,11598098,8847828,12170591,6079213,1477247,8071976,10741651,8611357
6,2956,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
7,3866,1249011,4613754,2387495,3324822,6024897,5694151,8018643,5037673,1753504,...,1127009,6620375,5477125,6234646,12221980,299329,3493209,4294570,1768627,12086034
8,7277,12398496,12546188,9081502,12248527,8726834,1371836,12068454,4464727,3909992,...,12204400,6164972,5559080,12411087,11551746,12097339,7374853,3944165,10221039,3685378
9,7944,2914440,5663620,7106394,11659460,2802947,12105494,10589759,9737917,862228,...,9986113,12081452,2996511,6000958,10500761,553107,6780014,10054931,3419377,11562365
10,8192,9889099,11614849,9400094,6895397,7790318,1034126,10405310,9154745,9124338,...,2321634,1035265,12972969,9551394,3634098,11768668,2609601,2969383,6208283,3738080
11,8408,9897425,9988978,12546188,9841467,12444849,12343099,2696686,10999359,10172820,...,9239734,11729651,11976954,10638479,215198,12226187,2720486,9181634,7380165,9171902
12,8464,8599864,23506,8590816,9004849,5250044,11986407,10430487,2257427,2553254,...,9291730,151444,7806302,4173806,10077662,6453839,4041604,3126084,9146037,3535394
13,8637,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
14,8760,12999698,7919399,596269,7195147,12587647,11507597,8846825,11321146,3983479,...,12492059,10189751,93250,7963279,5813336,3514490,11101005,12553498,8787223,5607178
15,9015,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
16,9035,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
17,9079,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
18,10146,2436741,2972303,612153,6953473,1074737,6112430,9779979,4574805,3993974,...,12012881,11190515,3224662,8897199,8425136,10313945,9398318,1529965,5822606,10345395
19,10836,11183791,8647059,317500,8376863,5897404,8927912,11394779,8086409,10967808,...,11271996,4218750,10768009,8535717,8291717,1480199,9835265,9732436,7964211,4731277
20,11092,425470,519838,582811,426384,5500389,3064373,5237546,829256,4987890,...,7851143,4647009,10012471,6460401,11432136,8755192,9224218,4652374,9558460,1025939
21,12072,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
22,13571,5097837,4906259,11613255,8122645,5421915,9067321,5738425,702838,9447580,...,5663042,863052,9008217,10513153,9127638,8580840,7448733,11778422,10826221,12059561
23,13851,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
24,14685,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
25,14757,9102655,4094167,3721193,2359145,6330400,9027307,7440027,11416195,8869549,...,3463558,10441426,1243283,11628997,12989602,6315471,10784041,10563050,674267,11098580
26,15114,10564906,10567252,2235262,4327035,5421915,1576768,11434316,1317065,2936140,...,5538805,7388461,9941498,3070008,10474913,10293353,9172085,13041405,5896183,8476773
27,15195,4322599,5096832,9990274,11532696,3398278,9324860,11340369,6478468,11107036,...,9120142,9809926,12670070,9970389,1224645,2862427,5309788,4054275,875587,8497727
28,17068,4018668,12867520,5553331,1884754,1711144,3724731,12139871,2487714,1066551,...,9789145,11432621,1673682,6915285,9556759,9131499,3738919,7616469,6990500,11115550
29,17141,12976183,7142470,10839420,6804558,2164665,1905116,1950716,4950362,11573110,...,10123708,6730136,4631005,7833755,5886128,7866894,4082485,12302817,7776645,2784832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11368,13008196,2772488,3989277,11422157,11189627,3674784,12394804,6852569,7781965,10845475,...,7763973,8056076,617246,10467010,10122348,3775697,1492024,11248308,2003831,3331388
11369,13024265,6029906,4774373,8776384,11052736,393498,5566896,3642225,12386708,904296,...,2894594,12296724,10834292,2880728,1435209,5090697,8226772,1708042,854867,9805427
11370,13024323,7027158,5073087,9887543,8460517,9582106,5039136,1004293,4379794,1663610,...,5250679,8867698,5927883,2601701,2075848,314190,11650188,1398554,9525283,3895791
11371,13024369,2439250,10302233,3028802,6445317,8306463,731331,2136805,4572306,5227013,...,958402,6948662,5319951,12290367,8086090,13001397,3423938,11999821,2641099,11449073
11372,13025072,8635384,13015528,4250410,9744043,1431232,2993383,1891540,3225200,8727980,...,11614129,10569609,9593795,11738412,241529,9403322,6456304,6791878,10209865,6876191
11373,13025986,3841099,12982902,5752532,5960062,13016623,12973896,12974355,8948357,12973909,...,13017109,4369113,12983219,9070793,8059045,11126614,2862612,9520867,12982887,2775410
11374,13026568,6701667,10315002,4859149,9989981,1899175,6195597,5838370,3426656,1004293,...,4469897,1660903,1981700,675524,9536362,11810668,2492173,8914979,3843819,8482294
11375,13027356,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
11376,13027430,11244075,828477,5173894,9925836,3392728,12427844,10664121,10761081,2080518,...,11650689,10467376,11527478,4055545,10450618,5955353,6993535,13040827,10843674,4721384
11377,13028759,11182373,5095804,4775222,9767549,9973449,9748961,9797794,669545,9903066,...,809824,11626901,12155842,6620847,9928615,3185301,9805066,2006166,6368144,8673319
11378,13028937,4904451,8206119,10836392,3364787,2877104,3492068,2917526,12564988,1424156,...,10225325,10034686,6848649,10265087,2451719,12195576,9561251,2781878,565286,11783369
11379,13028976,2290507,13016497,12982765,3878769,5845504,10064078,2191537,6433308,11470311,...,8990477,8815889,5678814,11835083,10913957,1965484,10983041,960994,2158807,10065173
11380,13029399,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
11381,13029522,7456825,7411615,6629711,1639456,6583383,624799,6419493,6773665,7280295,...,8257102,8307252,12823203,394127,5715194,1948215,6490542,4045754,6354849,9066416
11382,13029742,10452084,1966362,5580618,8018643,5205284,8768979,3446366,11155362,2977149,...,9247982,4744589,886696,2440537,2466249,9558460,5064136,3500888,8983348,11130839
11383,13029924,11672262,12408768,12928279,1563814,7631754,9686528,8863497,6334648,655248,...,8464941,6017460,12874150,6879113,3790875,7988074,5373757,5172840,4427303,12136747
11384,13029976,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
11385,13030926,1451046,11743474,6760611,11140901,9535804,11351251,1302947,6755490,6339286,...,945275,9271209,8349032,9357769,6223723,528247,9977218,10045561,7049764,4218750
11386,13032038,6596244,7198434,2437932,9274711,10384482,7992001,11167108,11042582,9541195,...,8267806,6948662,8433918,3056934,6569456,9160279,12842,8239459,1472230,10251626
11387,13034116,10365247,10815434,1507320,2546997,3406541,5702936,5104827,443400,9275181,...,9286523,4935544,3370134,1043015,5735739,4898487,6613309,2627340,11169829,7131071
11388,13035742,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
11389,13037285,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
11390,13037296,8860123,9831172,6519562,6666049,2115851,11617934,1515010,7210258,5663962,...,11476461,11786272,5619976,7371104,11416400,5877467,6610258,6138391,7042718,9201658
11391,13038422,4510673,9990274,3202740,5298497,8829276,377425,10855460,8061477,9100500,...,8738579,4737127,8306318,5450968,215198,9506917,9613191,6514672,760407,1395246
11392,13039625,3298820,2436741,6662644,10836392,3463038,1280777,9335601,10219789,4896012,...,570743,1766507,3683989,1688379,2328991,3197869,1044400,6315883,10265087,2572802
11393,13041046,5763716,11680030,1640397,5607460,10104308,4754732,9806613,10891457,10361748,...,10011151,11291525,10250220,2098597,10123462,10110190,11937988,3203287,10732440,10843674
11394,13041581,8595898,939520,5309308,2972034,11037323,4627976,8368084,5956570,4695246,...,11136064,12876054,6438202,8918937,8711161,8732449,6491935,2999709,6715881,10894655
11395,13044048,11778830,9437801,10647134,11680535,11901279,8203605,9925121,11948391,3685166,...,3862713,9800994,7244833,2262970,6098755,3452052,1151284,11963018,8533606,11931933
11396,13046354,10770051,5663620,7945295,9776214,11691391,7452293,10048793,9204254,7913705,...,12388549,7903408,11371541,5309788,11537462,9115297,10876691,10474913,12480883,6649223
11397,13046601,1319130,3900689,8814626,5517128,6478468,7282552,737317,6222224,7516439,...,7901647,6260025,5619538,12258004,624737,12961457,10491224,6963410,1653330,1542171

# 组合候选集

In [101]:
result_con = []
for idx,item in test_df_2.iterrows():
    tmp_lst = tmp2[tmp2['buyer_admin_id']==item.name]['item_id'].values.tolist()
    tmp_lst = tmp_lst + hot_item_10.index.values.tolist()
    tmp_lst = tmp_lst + result[result[0]==item.name].iloc[:,1:].values.tolist()[0]
    result_con.append([item.name]+tmp_lst)
result_con = pd.DataFrame(result_con)

In [110]:
result_con.fillna('5595070').iloc[:,:31].to_csv('../data/f_1.csv',index=False,header=None)