In [1]:
import pandas as pd

test_df = pd.read_csv('../data/Antai_AE_round1_test_20190626.csv')
print(test_df.shape[0])
test_df.head()

166832

  buyer_country_id  buyer_admin_id   item_id    create_order_time  irank
0               yy         1061132    189045  2018-07-17 07:43:40     18
1               yy         1081430  10713670  2018-07-17 09:43:15      8
2               yy         1918135  10546322  2018-07-17 11:11:34      9
3               yy          103277   5199603  2018-07-17 13:27:44     24
4               yy          103277   2477273  2018-07-17 13:27:44     22

In [2]:
import zipfile

# 默认模式r,读
train_zip = zipfile.ZipFile('../data/Antai_AE_round1_train_20190626.zip')
item_zip = zipfile.ZipFile('../data/Antai_AE_round1_item_attr_20190626.zip') 
print(train_zip.namelist())
print(item_zip.namelist())
train = train_zip.open('Antai_AE_round1_train_20190626.csv')
item = item_zip.open('Antai_AE_round1_item_attr_20190626.csv')

train_df = pd.read_csv(train)
item_df = pd.read_csv(item)

['Antai_AE_round1_train_20190626.csv']
['Antai_AE_round1_item_attr_20190626.csv']

In [3]:
train_yy = train_df[train_df['buyer_country_id']=='yy']
train_yy.head()

   buyer_country_id  buyer_admin_id  item_id    create_order_time  irank
2                yy          101887        3  2018-08-27 08:31:26      3
9                yy          288460        6  2018-08-31 13:41:25     11
10               yy          341958        6  2018-08-31 15:42:10      1
12               yy        12849617        6  2018-08-09 04:10:36     17
16               yy          770888        6  2018-08-31 23:33:54     12

In [37]:
train_yy['buyer_admin_id'].unique().shape[0]

138678

In [ ]:
# 历史

In [4]:
tmp = test_df[test_df['irank']<=31].sort_values(by=['buyer_country_id','buyer_admin_id','irank'])[['buyer_admin_id','item_id','irank']]
tmp.head()

       buyer_admin_id  item_id  irank
91354             152  8410857      2
91357             152  7937154      3
91352             152  8472223      4
91356             152  4016066      5
91353             152  9891513      6

In [ ]:
# 热销

In [5]:
hot_item_10 = pd.DataFrame(pd.concat([test_df,train_yy]).groupby(['item_id']).size(),columns=['cnt']).sort_values('cnt',ascending=False)[:10]
hot_item_10.head()

           cnt
item_id
11717821  1505
11140901  1492
5595070   1378
11680535  1337
2850195   1295

In [ ]:
# Item based

In [9]:
train_yy['create_order_time'] = train_yy.create_order_time.apply(lambda x:pd.to_datetime(x))
train_yy['hour'] = train_yy['create_order_time'].dt.hour
train_yy['date'] = train_yy['create_order_time'].dt.day
train_yy['month'] = train_yy['create_order_time'].dt.month
train_yy['year'] = train_yy['create_order_time'].dt.year
train_yy['month-date'] = train_yy.month.astype(str)+'-'+train_yy.date.astype(str)
train_yy['count'] = 1
train_yy['dayofweek'] = train_yy['create_order_time'].dt.dayofweek
train_yy['isweekend'] = train_yy['dayofweek'].apply(lambda x:0 if x<5 else 1)
train_yy.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

,buyer_country_id,buyer_admin_id,item_id,create_order_time,irank,hour,date,month,year,month-date,count,dayofweek,isweekend
2,yy,101887,3,2018-08-27 08:31:26,3,8,27,8,2018,8-27,1,0,0
9,yy,288460,6,2018-08-31 13:41:25,11,13,31,8,2018,8-31,1,4,0
10,yy,341958,6,2018-08-31 15:42:10,1,15,31,8,2018,8-31,1,4,0
12,yy,12849617,6,2018-08-09 04:10:36,17,4,9,8,2018,8-9,1,3,0
16,yy,770888,6,2018-08-31 23:33:54,12,23,31,8,2018,8-31,1,4,0

In [10]:
test_df['create_order_time'] = test_df.create_order_time.apply(lambda x:pd.to_datetime(x))
test_df['hour'] = test_df['create_order_time'].dt.hour
test_df['date'] = test_df['create_order_time'].dt.day
test_df['month'] = test_df['create_order_time'].dt.month
test_df['year'] = test_df['create_order_time'].dt.year
test_df['count'] = 1
test_df['month-date'] = test_df.month.astype(str)+'-'+test_df.date.astype(str)
test_df['dayofweek'] = test_df['create_order_time'].dt.dayofweek
test_df['isweekend'] = test_df['dayofweek'].apply(lambda x:0 if x<5 else 1)

In [12]:
test_df.head()

,buyer_country_id,buyer_admin_id,item_id,create_order_time,irank,hour,date,month,year,count,month-date,dayofweek,isweekend
0,yy,1061132,189045,2018-07-17 07:43:40,18,7,17,7,2018,1,7-17,1,0
1,yy,1081430,10713670,2018-07-17 09:43:15,8,9,17,7,2018,1,7-17,1,0
2,yy,1918135,10546322,2018-07-17 11:11:34,9,11,17,7,2018,1,7-17,1,0
3,yy,103277,5199603,2018-07-17 13:27:44,24,13,17,7,2018,1,7-17,1,0
4,yy,103277,2477273,2018-07-17 13:27:44,22,13,17,7,2018,1,7-17,1,0

In [28]:
train_yy[['buyer_admin_id','item_id']][:100]['item_id'].unique().shape

(55,)

In [30]:
user_based = UserBasedCF()

相似用户数目为 = 30
推荐Item数目为 = 30

In [31]:
user_based.generate_dataset(train_yy[['buyer_admin_id','item_id']][:100])

算法尝试！
split training set and test set succ
train set = 100
test set = 0

In [32]:
user_based.calc_user_sim()

构建物品-用户倒排表中，请等待......

构建物品-用户倒排表成功
总共被操作过的物品数目为 = 55
building user co-rated items matrix...
build user co-rated items matrix succ
calculating user similarity matrix...
calculate user similarity matrix(similarity factor) succ
Total similarity factor number = 256

In [33]:
user_based.evaluate()

Evaluation start...
recommended for 0 users

ZeroDivisionError: float division by zero

In [34]:
user_based.item_count

55

In [39]:
usercf_pred = UserBasedCF()
usercf_pred.generate_dataset(pd.concat([train_yy[['buyer_admin_id','item_id']],test_df[['buyer_admin_id','item_id']]]),
                             test_df[['buyer_admin_id','item_id']].drop_duplicates(subset=['buyer_admin_id'], keep='first'))
usercf_pred.calc_user_sim()

import pickle
output = open('./usercf_pred.pkl', 'wb')
pickle.dump(usercf_pred, output)
output.close()

相似用户数目为 = 10
推荐Item数目为 = 30

预测尝试！
split training set and test set succ
train set = 2399699
test set = 11398
构建物品-用户倒排表中，请等待......

构建物品-用户倒排表成功
总共被操作过的物品数目为 = 972388
building user co-rated items matrix...
build user co-rated items matrix succ
calculating user similarity matrix...
calculating user similarity factor(2000000)
calculating user similarity factor(4000000)
calculating user similarity factor(6000000)
calculating user similarity factor(8000000)
calculating user similarity factor(10000000)
calculating user similarity factor(12000000)
calculating user similarity factor(14000000)
calculating user similarity factor(16000000)
calculating user similarity factor(18000000)
calculating user similarity factor(20000000)
calculating user similarity factor(22000000)
calculating user similarity factor(24000000)
calculating user similarity factor(26000000)
calculate user similarity matrix(similarity factor) succ
Total similarity factor number = 27251402

In [40]:
result = usercf_pred.predict()
result_df = pd.DataFrame(result,columns=['buyer_admin_id','rec_items'])
result_df['rec_items'] = result_df.rec_items.apply(lambda x:[i[0] for i in x])
result_df['len'] = result_df.rec_items.apply(lambda x:len(x))

Predict start...
recommended for 0 users
recommended for 500 users
recommended for 1000 users
recommended for 1500 users
recommended for 2000 users
recommended for 2500 users
recommended for 3000 users
recommended for 3500 users
recommended for 4000 users
recommended for 4500 users
recommended for 5000 users
recommended for 5500 users
recommended for 6000 users
recommended for 6500 users
recommended for 7000 users
recommended for 7500 users
recommended for 8000 users
recommended for 8500 users
recommended for 9000 users
recommended for 9500 users
recommended for 10000 users
recommended for 10500 users
recommended for 11000 users
Predict end...

In [43]:
result_df.head()

       buyer_admin_id                                          rec_items  len
0             1061132  [1992350, 1207574, 189045, 11271996, 1516143, ...   30
1             1081430  [4109174, 822359, 9932432, 10184371, 11565882,...   30
2             1918135  [10546322, 2724688, 3239694, 5939557, 6079606,...   30
3              103277  [7563496, 3993974, 7481939, 10743206, 7785543,...   30
4             1957158  [1214872, 1397346, 6766255, 4955926, 5702107, ...   30
5             1376989  [9972220, 11790053, 8694133, 410019, 1551855, ...   30
6             1563046  [2434940, 8516922, 10035229, 8300510, 7068791,...   30
7             1280264  [3866632, 9388436, 11545249, 5133006, 695628, ...   28
8              104145  [1433894, 3197976, 5362349, 1236358, 1291401, ...   30
9              850637  [7017123, 10251187, 10622895, 10686858, 119543...   30
10            1135064  [10433903, 8099239, 10300735, 10492522, 108251...   30
11            2302927  [7521360, 3375401, 2641569, 2620657, 5191840, ...   30
12            1152117  [5973981, 7698995, 5786972, 9788190, 10104079,...   30
13             570640  [9299908, 2392165, 10491948, 7370949, 269849, ...   30
14            1917676  [6423473, 4976805, 5485826, 6381790, 11980433,...   30
15            1944372  [10175288, 8685503, 758341, 2393188, 4097780, ...   30
16             235457  [12314621, 12177522, 11677603, 4792153, 575401...   30
17            1746023  [4797146, 7118512, 12816323, 8368304, 12406203...   30
18             406801  [10516392, 1727672, 283107, 4522268, 8141361, ...   30
19             230941  [6783037, 526826, 3575829, 2318992, 4937239, 8...   30
20            1553497  [7663592, 9535410, 10151922, 10156269, 480658,...   30
21             982049  [625121, 625186, 10192310, 7350995, 3039739, 8...   30
22            1000927  [8920282, 11375859, 10529296, 11236113, 129789...   30
23             730501  [9023224, 6619730, 9161396, 3591180, 6194866, ...   30
24             135882  [6457140, 10176518, 9461975, 7979097, 1244150,...   30
25             653027  [10060924, 5668704, 2946480, 4658641, 9604575,...   30
26            2161973  [9756464, 9973016, 1196016, 10353218, 10883836...   30
27            1594372  [11982814, 13035167, 5135820, 9974770, 1047071...   30
28             723249  [5553235, 480325, 4868643, 7550926, 9064398, 1...   30
29             503825  [11932296, 8815059, 12577021, 11526051, 249217...   30
...               ...                                                ...  ...
11368         1764504  [2249889, 5777955, 8525615, 2395805, 5901899, ...   30
11369         2203284  [1302947, 9560030, 8869187, 6161792, 9359967, ...   30
11370         1128243  [8269599, 9567033, 12152275, 9259141, 2107553,...   30
11371          847003  [10140500, 10752801, 6926374, 8249320, 9256396...   30
11372         2053089  [2307482, 7393913, 1761912, 3547573, 6684037, ...   30
11373         1439342  [12093615, 10025910, 3220756, 3850628, 7155403...   30
11374         2212230  [6025215, 9907121, 5726997, 2133349, 2925223, ...   29
11375          305285  [8195907, 11715056, 541572, 9133572, 10072371,...   30
11376          994361  [6497924, 8834769, 1261389, 11291525, 1891295,...   30
11377          960146  [11526051, 11412401, 10126085, 1695358, 305306...   30
11378         2179759  [3334215, 4536110, 1994006, 2972034, 5534385, ...   30
11379         1785549  [2138353, 8837122, 8117410, 6689674, 11148805,...   30
11380         2134165  [11538073, 2541425, 5432024, 11028413, 6129840...   30
11381         2145746  [8422914, 9775459, 3159240, 4880617, 1857878, ...   30
11382          478657  [4396852, 3037124, 1755044, 2975295, 3569752, ...   30
11383         1775754  [6025215, 3362266, 9907121, 7473388, 3625959, ...   30
11384          748015  [6663274, 12607973, 602156, 1234973, 3059563, ...   30
11385          394913                                                 []    0
11386          227724  [11845247, 2132560, 7977628, 8200028, 2927321,...   30
11387         1283974  [9897114, 6318438, 12543540, 319264, 651168, 5...   30
11388          385591  [372521, 2863365, 3762803, 3764814, 6717763, 5...   30
11389          524369  [4848097, 7471819, 5063581, 5300877, 9872494, ...   30
11390         1688905  [11201409, 2156012, 5445745, 8069568, 8647480,...   30
11391         2361324  [3140148, 620653, 1271763, 7533238, 1013112, 6...   30
11392         1931205  [9354413, 1427684, 3514289, 4394247, 4947024, ...   30
11393          419958  [1291401, 268820, 2393398, 2895381, 3025407, 3...   30
11394         1242965  [6188307, 384877, 426384, 1194558, 1197459, 21...   30
11395          962939  [7151390, 8297443, 6025215, 7661956, 3096187, ...   30
11396         1243416  [7720560, 1666365, 7634786, 1563814, 1937716, ...   30
11397         2150916  [5064674, 12037837, 5378739, 8511839, 9760979,...   30

[11398 rows x 3 columns]

In [49]:
sorted(usercf_pred.item_popular.items(), key=lambda obj: obj[1],reverse=True)

[(11291525, 835),
 (10788165, 772),
 (6025215, 676),
 (10868663, 576),
 (11717821, 562),
 (2850195, 468),
 (2191537, 467),
 (11140901, 464),
 (3227771, 456),
 (12626807, 449),
 (9414379, 429),
 (9907121, 419),
 (9537542, 396),
 (3866632, 394),
 (11680535, 392),
 (7495308, 387),
 (7498078, 384),
 (13038480, 379),
 (13040827, 377),
 (6112486, 372),
 (8580840, 348),
 (8980792, 342),
 (1555732, 340),
 (12928279, 311),
 (10525626, 308),
 (13018359, 303),
 (12120132, 298),
 (908415, 291),
 (9582192, 284),
 (1359800, 278),
 (2249889, 278),
 (10244477, 275),
 (6887593, 272),
 (1933438, 257),
 (11282455, 257),
 (10342698, 257),
 (9430299, 256),
 (7709098, 252),
 (4987890, 252),
 (7849185, 251),
 (10999359, 248),
 (11526051, 241),
 (1066551, 239),
 (4686925, 237),
 (9789145, 235),
 (6990614, 234),
 (10761081, 233),
 (6057436, 232),
 (1382347, 229),
 (10110190, 227),
 (4647009, 221),
 (682988, 219),
 (10017778, 219),
 (3362266, 218),
 (8820011, 217),
 (5031616, 214),
 (671722, 214),
 (7539810, 213),
 (7563496, 212),
 (8081951, 211),
 (10094245, 209),
 (1273217, 208),
 (12939345, 207),
 (11887820, 205),
 (8269599, 204),
 (11798458, 202),
 (11955903, 200),
 (4228107, 200),
 (277654, 199),
 (12980730, 199),
 (7223628, 199),
 (945275, 199),
 (10517552, 196),
 (3993974, 195),
 (2953605, 195),
 (6944208, 195),
 (5214489, 192),
 (12877155, 191),
 (1492024, 186),
 (9951478, 185),
 (10487212, 185),
 (10538002, 184),
 (7944545, 184),
 (4510673, 184),
 (9925121, 183),
 (9841579, 182),
 (11533456, 181),
 (9215251, 181),
 (3086129, 181),
 (10140500, 180),
 (6119471, 178),
 (3651678, 178),
 (12175967, 177),
 (3414666, 177),
 (11559746, 177),
 (9494111, 176),
 (10617258, 176),
 (7880047, 175),
 (468907, 174),
 (9040624, 174),
 (10060924, 174),
 (5886962, 174),
 (2784832, 173),
 (5884178, 173),
 (10692087, 173),
 (8117410, 172),
 (8844287, 172),
 (11459382, 172),
 (6161792, 171),
 (9704545, 170),
 (10371557, 170),
 (6935456, 170),
 (9958362, 170),
 (12152275, 170),
 (2692258, 169),
 (7514606, 169),
 (10742436, 168),
 (1013112, 168),
 (13041405, 167),
 (8927994, 166),
 (7678520, 166),
 (11980433, 166),
 (9096905, 165),
 (10000188, 165),
 (5133006, 163),
 (10516392, 162),
 (2080518, 162),
 (8964918, 161),
 (9417750, 161),
 (10688188, 161),
 (9104539, 160),
 (5506462, 159),
 (7613920, 158),
 (5390071, 158),
 (956425, 157),
 (11778830, 156),
 (12184735, 156),
 (9151415, 155),
 (343490, 155),
 (2158807, 154),
 (7431033, 154),
 (10072371, 154),
 (7629746, 154),
 (7550926, 154),
 (10651268, 154),
 (11545249, 152),
 (611267, 152),
 (7118512, 152),
 (4867093, 152),
 (1357648, 150),
 (7533238, 149),
 (10117452, 148),
 (5694367, 148),
 (9132176, 148),
 (2660275, 148),
 (12878628, 148),
 (9767549, 147),
 (9548672, 147),
 (6843799, 147),
 (5945746, 146),
 (276546, 146),
 (10166752, 145),
 (10313945, 145),
 (10238995, 145),
 (5150173, 144),
 (2558503, 144),
 (3509561, 144),
 (6462948, 144),
 (6089604, 144),
 (10914170, 143),
 (13006287, 142),
 (692592, 142),
 (10045561, 142),
 (8954162, 142),
 (10122621, 141),
 (9711280, 141),
 (9958079, 141),
 (10716329, 141),
 (9409231, 140),
 (3117887, 140),
 (12940460, 140),
 (9592696, 140),
 (2630133, 140),
 (9853093, 140),
 (8492717, 139),
 (10420044, 138),
 (10723906, 138),
 (8716590, 138),
 (7390092, 137),
 (1482396, 137),
 (1174197, 137),
 (12402865, 137),
 (6262103, 135),
 (3564745, 135),
 (4274467, 135),
 (6167936, 135),
 (7198434, 134),
 (7931530, 134),
 (3446366, 133),
 (6283374, 133),
 (6661755, 132),
 (11148021, 132),
 (8212858, 132),
 (764094, 131),
 (9560030, 131),
 (7872169, 131),
 (3337768, 131),
 (9239734, 130),
 (3775697, 130),
 (4000593, 129),
 (394127, 129),
 (9918649, 129),
 (3801666, 128),
 (10011497, 128),
 (1226993, 128),
 (11891955, 127),
 (480325, 127),
 (10719712, 126),
 (10764878, 126),
 (10998391, 126),
 (7125223, 126),
 (7107651, 126),
 (2914440, 125),
 (12419011, 125),
 (8951229, 125),
 (5845504, 125),
 (8443514, 124),
 (1711144, 124),
 (9927629, 124),
 (10717161, 123),
 (9297752, 123),
 (12116004, 123),
 (5378133, 123),
 (426384, 122),
 (9574451, 122),
 (8622107, 122),
 (9271209, 122),
 (502865, 121),
 (11813288, 121),
 (10994755, 121),
 (11659460, 121),
 (5934739, 120),
 (9445538, 120),
 (10801347, 120),
 (11115550, 120),
 (12186711, 120),
 (11449073, 120),
 (9108322, 120),
 (11044689, 119),
 (12328696, 119),
 (8834769, 119),
 (8753413, 119),
 (105938, 119),
 (4461288, 119),
 (8694133, 119),
 (9558460, 118),
 (1561081, 118),
 (10424369, 118),
 (9018504, 118),
 (10173317, 118),
 (8345489, 118),
 (4935544, 117),
 (2940765, 117),
 (8569346, 117),
 (3606490, 117),
 (1865506, 117),
 (7866114, 117),
 (9520937, 117),
 (7088491, 116),
 (6450865, 116),
 (8869187, 116),
 (10098025, 116),
 (7057863, 115),
 (8897735, 115),
 (11551543, 115),
 (9587042, 115),
 (9475710, 114),
 (3802721, 114),
 (6072508, 114),
 (10120244, 114),
 (7880579, 114),
 (3289392, 113),
 (9805066, 113),
 (9730480, 113),
 (3111202, 113),
 (229937, 113),
 (2109162, 113),
 (11341806, 113),
 (8139992, 112),
 (11479423, 112),
 (5193037, 112),
 (12653622, 112),
 (10086016, 112),
 (7666720, 112),
 (4080011, 112),
 (9323998, 111),
 (515498, 111),
 (9703881, 111),
 (5610461, 111),
 (7668726, 111),
 (3561109, 111),
 (4259583, 111),
 (5444963, 110),
 (2003831, 110),
 (3770740, 110),
 (3834135, 110),
 (9370498, 110),
 (10556658, 110),
 (8157634, 110),
 (8733302, 110),
 (7963279, 110),
 (3975130, 110),
 (317500, 109),
 (8223106, 109),
 (9507437, 109),
 (2972034, 109),
 (9833768, 109),
 (2724688, 108),
 (9083612, 108),
 (8180860, 108),
 (11422157, 108),
 (6926374, 108),
 (76422, 107),
 (7847626, 107),
 (8920282, 107),
 (7741356, 107),
 (10014488, 107),
 (9112610, 107),
 (11088820, 107),
 (12243487, 107),
 (7293416, 106),
 (10554725, 106),
 (1708042, 106),
 (10638479, 106),
 (3579673, 106),
 (4848097, 106),
 (7734985, 105),
 (4218750, 105),
 (5668704, 105),
 (5017824, 105),
 (1446341, 105),
 (2230633, 105),
 (2913204, 105),
 (10176518, 105),
 (8244245, 104),
 (9858509, 104),
 (12980963, 104),
 (9178438, 104),
 (9052525, 104),
 (1507320, 104),
 (7625420, 103),
 (10572757, 103),
 (3500888, 103),
 (2030802, 103),
 (12643178, 103),
 (6628246, 103),
 (2665441, 103),
 (12010704, 103),
 (3597536, 102),
 (1576768, 102),
 (4162586, 102),
 (3612060, 102),
 (6596244, 102),
 (9616409, 102),
 (8957728, 102),
 (11077830, 102),
 (6051900, 102),
 (10843674, 101),
 (8860209, 101),
 (9601000, 101),
 (541572, 101),
 (8794830, 101),
 (8005801, 101),
 (10752801, 101),
 (7690073, 101),
 (6350221, 100),
 (7958148, 100),
 (9206271, 100),
 (10842595, 100),
 (2601093, 100),
 (6122068, 100),
 (12556593, 100),
 (12959089, 100),
 (11083354, 99),
 (10011151, 99),
 (10564906, 99),
 (9604575, 99),
 (9766507, 99),
 (9722278, 99),
 (7949611, 99),
 (5629651, 99),
 (4538161, 99),
 (9308112, 98),
 (7994277, 98),
 (11976229, 98),
 (6879505, 98),
 (9770922, 98),
 (8604659, 98),
 (5611991, 98),
 (6904157, 98),
 (7437487, 97),
 (5517128, 97),
 (2460043, 96),
 (9590117, 96),
 (10100751, 96),
 (7097841, 96),
 (10368739, 96),
 (10245504, 95),
 (6317125, 95),
 (5633430, 95),
 (2899642, 95),
 (9314251, 95),
 (12089943, 95),
 (1450033, 95),
 (9883379, 95),
 (9872494, 95),
 (3817351, 94),
 (10065384, 94),
 (228937, 94),
 (226972, 94),
 (12358050, 94),
 (7050916, 94),
 (8018643, 94),
 (10946161, 94),
 (10214551, 94),
 (5309788, 94),
 (2488253, 94),
 (8463489, 94),
 (12569449, 94),
 (9378713, 94),
 (6849340, 94),
 (10547303, 94),
 (6364901, 94),
 (9739063, 93),
 (10449218, 93),
 (6758751, 93),
 (1302947, 93),
 (5991060, 93),
 (6791878, 93),
 (12553498, 93),
 (5288368, 93),
 (4187447, 93),
 (10799659, 93),
 (2236565, 93),
 (10709957, 93),
 (10779791, 93),
 (5664567, 93),
 (2370323, 92),
 (731915, 92),
 (6767983, 92),
 (8695087, 92),
 (10052772, 92),
 (12065011, 92),
 (9081502, 92),
 (11190515, 91),
 (2894994, 91),
 (9712625, 91),
 (1291401, 91),
 (7408394, 91),
 (2832058, 91),
 (4454589, 91),
 (264727, 91),
 (11756494, 91),
 (1589650, 90),
 (11768668, 90),
 (9369077, 90),
 (9391451, 90),
 (3140148, 90),
 (7133156, 90),
 (5702107, 90),
 (1600495, 89),
 (12991650, 89),
 (7855696, 89),
 (10383491, 89),
 (3145723, 89),
 (9963547, 89),
 (10815434, 89),
 (322324, 89),
 (8277336, 89),
 (9802639, 89),
 (12127372, 89),
 (5256345, 88),
 (10362566, 88),
 (5369445, 88),
 (9435808, 88),
 (8203887, 88),
 (11527805, 87),
 (10480027, 87),
 (10445011, 87),
 (5766692, 87),
 (296127, 87),
 (2020763, 87),
 (3445506, 87),
 (2174706, 87),
 (5901899, 87),
 (8202902, 87),
 (8301698, 87),
 (775056, 87),
 (1627457, 86),
 (5016352, 86),
 (8205423, 86),
 (8977820, 86),
 (3686066, 86),
 (9064398, 86),
 (2359145, 86),
 (1981700, 86),
 (7602014, 86),
 (3469455, 86),
 (7832138, 86),
 (8137251, 86),
 (2841815, 86),
 (6437206, 86),
 (11271996, 85),
 (8868558, 85),
 (12937258, 85),
 (7312631, 85),
 (6361227, 85),
 (1797747, 85),
 (10632282, 85),
 (10083234, 85),
 (10307545, 85),
 (241529, 85),
 (2785459, 85),
 (10589759, 85),
 (8035201, 84),
 (675524, 84),
 (11701996, 84),
 (6038299, 84),
 (8807689, 84),
 (6724365, 84),
 (3331388, 84),
 (4370821, 84),
 (3209329, 84),
 (12070535, 84),
 (4434839, 84),
 (851144, 83),
 (11821350, 83),
 (7211880, 83),
 (11007793, 83),
 (1380195, 83),
 (8042846, 83),
 (7356284, 83),
 (3047120, 83),
 (8468748, 83),
 (215819, 83),
 (5588232, 83),
 (12485298, 83),
 (3354, 82),
 (8330476, 82),
 (11876378, 82),
 (9461975, 82),
 (4427303, 82),
 (9138627, 82),
 (5550644, 82),
 (9224218, 82),
 (1670222, 82),
 (4803442, 82),
 (11954324, 82),
 (5864445, 82),
 (10074514, 82),
 (7677128, 81),
 (9891513, 81),
 (5625302, 81),
 (3648372, 81),
 (13001164, 81),
 (10523631, 81),
 (7430477, 81),
 (12618710, 81),
 (10605099, 81),
 (10845475, 81),
 (10249801, 81),
 (6786444, 81),
 (1628535, 81),
 (12968597, 81),
 (11527478, 80),
 (6600260, 80),
 (5028775, 80),
 (6142807, 80),
 (9329267, 80),
 (5295817, 80),
 (9422206, 80),
 (5096062, 80),
 (9691980, 80),
 (4361419, 80),
 (6680629, 80),
 (11810668, 80),
 (9050805, 80),
 (11590126, 80),
 (2283755, 80),
 (770769, 80),
 (11703635, 80),
 (3728970, 80),
 (7647779, 80),
 (2810141, 80),
 (9483018, 80),
 (5126628, 80),
 (3398278, 80),
 (10610692, 79),
 (7544100, 79),
 (10662606, 79),
 (8645917, 79),
 (1445407, 79),
 (2104401, 79),
 (11450851, 79),
 (8021578, 79),
 (8286698, 79),
 (5860911, 79),
 (1590781, 79),
 (11014566, 79),
 (6783037, 79),
 (6532598, 79),
 (8664870, 79),
 (7505039, 79),
 (3553867, 79),
 (11347712, 79),
 (2759133, 79),
 (5496186, 79),
 (8925813, 79),
 (256399, 78),
 (7992001, 78),
 (4560533, 78),
 (6252069, 78),
 (7239587, 78),
 (1638562, 78),
 (5840372, 78),
 (12210664, 78),
 (9739999, 78),
 (10923159, 78),
 (12566900, 78),
 (9523318, 78),
 (8429523, 77),
 (5317017, 77),
 (9388436, 77),
 (8392244, 77),
 (364580, 77),
 (9539771, 77),
 (483808, 77),
 (479013, 77),
 (6620941, 77),
 (6915285, 77),
 (3536149, 77),
 (1755687, 77),
 (419280, 77),
 (3814357, 77),
 (10442878, 76),
 (10596611, 76),
 (3540718, 76),
 (7131071, 76),
 (6440011, 76),
 (6847420, 76),
 (6622206, 76),
 (6662098, 76),
 (8950245, 76),
 (2098597, 75),
 (7833920, 75),
 (3213479, 75),
 (12652208, 75),
 (651168, 75),
 (3239694, 75),
 (7627200, 75),
 (1851990, 75),
 (7096576, 75),
 (4394681, 75),
 (8489304, 75),
 (5623650, 75),
 (1563814, 75),
 (1930547, 75),
 (1820443, 75),
 (2651158, 75),
 (9926867, 75),
 (9968723, 75),
 (9827953, 75),
 (1147187, 75),
 (7763973, 75),
 (10813989, 75),
 (2172964, 75),
 (12156207, 75),
 (7029142, 74),
 (2938525, 74),
 (6133826, 74),
 (8722265, 74),
 (1314730, 74),
 (5873609, 74),
 (7833755, 74),
 (11285491, 74),
 (11445793, 74),
 (9299908, 74),
 (3355943, 74),
 (9613191, 74),
 (4292374, 74),
 (12237555, 74),
 (7829059, 74),
 (7465951, 74),
 (315864, 74),
 (1866161, 74),
 (1056696, 74),
 (5822606, 74),
 (4310981, 74),
 (7846350, 73),
 (8784270, 73),
 (933622, 73),
 (2901886, 73),
 (47426, 73),
 (9240896, 73),
 (9331611, 73),
 (1472655, 73),
 (8024394, 73),
 (4972380, 73),
 (1620820, 73),
 (3522309, 73),
 (3733359, 73),
 (151444, 73),
 (7169121, 73),
 (9123396, 73),
 (10976037, 73),
 (11127108, 73),
 (5939557, 73),
 (6495818, 73),
 (8440790, 73),
 (5500389, 73),
 (11016201, 73),
 (2420193, 72),
 (8674142, 72),
 (10459781, 72),
 (809161, 72),
 (7406668, 72),
 (5994090, 72),
 (8915293, 72),
 (9336696, 72),
 (5782207, 72),
 (10385337, 72),
 (9031148, 72),
 (10712593, 72),
 (6740664, 72),
 (2081517, 72),
 (12305036, 72),
 (5725248, 72),
 (9044030, 72),
 (4420682, 71),
 (1039726, 71),
 (11588836, 71),
 (7798969, 71),
 (1750657, 71),
 (5672365, 71),
 (9471675, 71),
 (9190977, 71),
 (11511726, 71),
 (10244381, 71),
 (7280295, 71),
 (10152968, 71),
 (9033085, 71),
 (12195576, 71),
 (12935544, 71),
 (5638239, 71),
 (1666365, 71),
 (2492173, 71),
 (11783831, 71),
 (8255033, 71),
 (3364787, 71),
 (2920843, 71),
 (9938439, 71),
 (146472, 71),
 (6427709, 71),
 (10936248, 71),
 (8845468, 71),
 (10529296, 70),
 (9504542, 70),
 (2958064, 70),
 (5277380, 70),
 (12139871, 70),
 (7285772, 70),
 (7204203, 70),
 (3974726, 70),
 (2099559, 70),
 (5502267, 70),
 (1202226, 70),
 (6846103, 70),
 (620653, 70),
 (10096979, 70),
 (9255847, 70),
 (5581937, 70),
 (5747532, 70),
 (12289200, 70),
 (2536516, 70),
 (9273591, 70),
 (5054386, 70),
 (6454501, 70),
 (3607872, 69),
 (5733932, 69),
 (4094538, 69),
 (9832871, 69),
 (3257419, 69),
 (7263975, 69),
 (10569609, 69),
 (11307815, 69),
 (2457134, 69),
 (2946809, 69),
 (3122160, 69),
 (10375724, 69),
 (10657969, 69),
 (9266242, 69),
 (8969387, 69),
 (5853506, 69),
 (3493209, 69),
 (3495767, 69),
 (8946537, 69),
 (5596677, 69),
 (4380763, 69),
 (496093, 69),
 (8426050, 68),
 (5088115, 68),
 (9720176, 68),
 (3826586, 68),
 (10732440, 68),
 (10656237, 68),
 (8135460, 68),
 (4834091, 68),
 (9973449, 68),
 (12499613, 68),
 (3938121, 68),
 (6137778, 68),
 (4407975, 68),
 (5499567, 68),
 (9544528, 68),
 (3393306, 68),
 (3187683, 68),
 (5808800, 68),
 (12079952, 68),
 (10233388, 68),
 (11887432, 67),
 (11313969, 67),
 (10671895, 67),
 (5483389, 67),
 (8424491, 67),
 (13013421, 67),
 (2983480, 67),
 (10800347, 67),
 (3954264, 67),
 (9363695, 67),
 (8596871, 67),
 (1869774, 67),
 (7442635, 67),
 (11558118, 67),
 (4950362, 67),
 (7445615, 67),
 (733861, 67),
 (7515121, 67),
 (6111347, 67),
 (8139011, 67),
 (7568763, 67),
 (11644655, 67),
 (7728801, 66),
 (9146037, 66),
 (3043480, 66),
 (8885644, 66),
 (9482544, 66),
 (6910408, 66),
 (9669610, 66),
 (10486456, 66),
 (7573551, 66),
 (2449262, 66),
 (1608877, 66),
 (9851922, 66),
 (8576022, 66),
 (4945327, 66),
 (11873675, 66),
 (1558039, 66),
 (3116156, 66),
 (6699836, 66),
 (3045462, 66),
 (12985419, 66),
 (6396128, 66),
 (10113026, 66),
 (10837563, 66),
 (4539916, 66),
 (7242263, 65),
 (2248, 65),
 (2885705, 65),
 (377425, 65),
 (1122746, 65),
 (4633703, 65),
 (8099239, 65),
 (1805118, 65),
 (6433308, 65),
 (3379550, 65),
 (2316426, 65),
 (7724128, 65),
 (11945185, 65),
 (2086048, 65),
 (10441571, 65),
 (9159040, 65),
 (10369514, 65),
 (4050279, 65),
 (10374802, 65),
 (12938735, 64),
 (12329095, 64),
 (10299386, 64),
 (6222556, 64),
 (4350767, 64),
 (7106394, 64),
 (3756910, 64),
 (9567033, 64),
 (3132374, 64),
 (4413657, 64),
 (7610585, 64),
 (11713731, 64),
 (11175579, 64),
 (10700217, 64),
 (13014242, 64),
 (8766721, 64),
 (10301680, 64),
 (2668792, 64),
 (305515, 64),
 (7773572, 64),
 (634028, 64),
 (7657236, 64),
 (6113747, 64),
 (2402615, 64),
 (12253922, 64),
 (8291717, 64),
 (11857503, 64),
 (6576214, 63),
 (4449652, 63),
 (7720560, 63),
 (11620164, 63),
 (9798100, 63),
 (7529240, 63),
 (3265290, 63),
 (4015006, 63),
 (207582, 63),
 (7082163, 63),
 (7681963, 63),
 (3723220, 63),
 (6366882, 63),
 (9252706, 63),
 (6521913, 63),
 (8005488, 63),
 (1421905, 63),
 (8955057, 63),
 (1753504, 63),
 (7026436, 63),
 (10381946, 63),
 (4743625, 63),
 (9362091, 63),
 (3081512, 63),
 (10260768, 63),
 (6443250, 63),
 (1210732, 63),
 (12640976, 62),
 (12086034, 62),
 (6426586, 62),
 (10229772, 62),
 (11504334, 62),
 (3660746, 62),
 (3075546, 62),
 (9256396, 62),
 (11697887, 62),
 (10583050, 62),
 (11448903, 62),
 (10116529, 62),
 (7874917, 62),
 (6359948, 62),
 (4652374, 61),
 (11306656, 61),
 (3985427, 61),
 (8249320, 61),
 (6457140, 61),
 (8230512, 61),
 (7634786, 61),
 (12299493, 61),
 (11660971, 61),
 (10281170, 61),
 (8326122, 61),
 (6284195, 61),
 (7296526, 61),
 (5531535, 61),
 (2132190, 61),
 (8681205, 61),
 (4600190, 61),
 (2036473, 61),
 (10731958, 61),
 (6541336, 61),
 (10752508, 61),
 (4006417, 61),
 (6744428, 61),
 (1331665, 61),
 (4396852, 61),
 (3851532, 61),
 (1501237, 61),
 (8907807, 61),
 (6962654, 61),
 (4299068, 61),
 (10556546, 61),
 (10104308, 61),
 (9841058, 61),
 (8050942, 61),
 (1344549, 60),
 (255267, 60),
 (10508135, 60),
 (193486, 60),
 ...]

In [ ]:
# Item based

In [45]:
itemcf_pred = UserBasedCF()
itemcf_pred.generate_dataset(pd.concat([train_yy[['item_id','buyer_admin_id']],test_df[['item_id','buyer_admin_id']]]),
                             test_df[['item_id','buyer_admin_id']].drop_duplicates(subset=['item_id'], keep='first'))
itemcf_pred.calc_user_sim()

import pickle
output = open('./itemcf_pred.pkl', 'wb')
pickle.dump(itemcf_pred, output)
output.close()

相似用户数目为 = 10
推荐Item数目为 = 30

预测尝试！
split training set and test set succ
train set = 2399699
test set = 104735
构建物品-用户倒排表中，请等待......

构建物品-用户倒排表成功
总共被操作过的物品数目为 = 150076
building user co-rated items matrix...
build user co-rated items matrix succ
calculating user similarity matrix...
calculating user similarity factor(2000000)
calculating user similarity factor(4000000)
calculating user similarity factor(6000000)
calculating user similarity factor(8000000)
calculating user similarity factor(10000000)
calculating user similarity factor(12000000)
calculating user similarity factor(14000000)
calculating user similarity factor(16000000)
calculating user similarity factor(18000000)
calculating user similarity factor(20000000)
calculating user similarity factor(22000000)
calculating user similarity factor(24000000)
calculating user similarity factor(26000000)
calculating user similarity factor(28000000)
calculating user similarity factor(30000000)
calculating user similarity factor(32000000)
calculating user similarity factor(34000000)
calculating user similarity factor(36000000)
calculating user similarity factor(38000000)
calculating user similarity factor(40000000)
calculate user similarity matrix(similarity factor) succ
Total similarity factor number = 41031882

In [47]:
result_1 = itemcf_pred.predict()
result_1_df = pd.DataFrame(result_1,columns=['item_id','rec_users'])
result_1_df['rec_items'] = result_1_df.rec_users.apply(lambda x:[i[0] for i in x])
result_1_df['len'] = result_1_df.rec_users.apply(lambda x:len(x))
result_1_df

Predict start...
recommended for 0 users
recommended for 500 users
recommended for 1000 users
recommended for 1500 users
recommended for 2000 users
recommended for 2500 users
recommended for 3000 users
recommended for 3500 users
recommended for 4000 users
recommended for 4500 users
recommended for 5000 users
recommended for 5500 users
recommended for 6000 users
recommended for 6500 users
recommended for 7000 users
recommended for 7500 users
recommended for 8000 users
recommended for 8500 users
recommended for 9000 users
recommended for 9500 users
recommended for 10000 users
recommended for 10500 users
recommended for 11000 users
recommended for 11500 users
recommended for 12000 users
recommended for 12500 users
recommended for 13000 users
recommended for 13500 users
recommended for 14000 users
recommended for 14500 users
recommended for 15000 users
recommended for 15500 users
recommended for 16000 users
recommended for 16500 users
recommended for 17000 users
recommended for 17500 users
recommended for 18000 users
recommended for 18500 users
recommended for 19000 users
recommended for 19500 users
recommended for 20000 users
recommended for 20500 users
recommended for 21000 users
recommended for 21500 users
recommended for 22000 users
recommended for 22500 users
recommended for 23000 users
recommended for 23500 users
recommended for 24000 users
recommended for 24500 users
recommended for 25000 users
recommended for 25500 users
recommended for 26000 users
recommended for 26500 users
recommended for 27000 users
recommended for 27500 users
recommended for 28000 users
recommended for 28500 users
recommended for 29000 users
recommended for 29500 users
recommended for 30000 users
recommended for 30500 users
recommended for 31000 users
recommended for 31500 users
recommended for 32000 users
recommended for 32500 users
recommended for 33000 users
recommended for 33500 users
recommended for 34000 users
recommended for 34500 users
recommended for 35000 users
recommended for 35500 users
recommended for 36000 users
recommended for 36500 users
recommended for 37000 users
recommended for 37500 users
recommended for 38000 users
recommended for 38500 users
recommended for 39000 users
recommended for 39500 users
recommended for 40000 users
recommended for 40500 users
recommended for 41000 users
recommended for 41500 users
recommended for 42000 users
recommended for 42500 users
recommended for 43000 users
recommended for 43500 users
recommended for 44000 users
recommended for 44500 users
recommended for 45000 users
recommended for 45500 users
recommended for 46000 users
recommended for 46500 users
recommended for 47000 users
recommended for 47500 users
recommended for 48000 users
recommended for 48500 users
recommended for 49000 users
recommended for 49500 users
recommended for 50000 users
recommended for 50500 users
recommended for 51000 users
recommended for 51500 users
recommended for 52000 users
recommended for 52500 users
recommended for 53000 users
recommended for 53500 users
recommended for 54000 users
recommended for 54500 users
recommended for 55000 users
recommended for 55500 users
recommended for 56000 users
recommended for 56500 users
recommended for 57000 users
recommended for 57500 users
recommended for 58000 users
recommended for 58500 users
recommended for 59000 users
recommended for 59500 users
recommended for 60000 users
recommended for 60500 users
recommended for 61000 users
recommended for 61500 users
recommended for 62000 users
recommended for 62500 users
recommended for 63000 users
recommended for 63500 users
recommended for 64000 users
recommended for 64500 users
recommended for 65000 users
recommended for 65500 users
recommended for 66000 users
recommended for 66500 users
recommended for 67000 users
recommended for 67500 users
recommended for 68000 users
recommended for 68500 users
recommended for 69000 users
recommended for 69500 users
recommended for 70000 users
recommended for 70500 users
recommended for 71000 users
recommended for 71500 users
recommended for 72000 users
recommended for 72500 users
recommended for 73000 users
recommended for 73500 users
recommended for 74000 users
recommended for 74500 users
recommended for 75000 users
recommended for 75500 users
recommended for 76000 users
recommended for 76500 users
recommended for 77000 users
recommended for 77500 users
recommended for 78000 users
recommended for 78500 users
recommended for 79000 users
recommended for 79500 users
recommended for 80000 users
recommended for 80500 users
recommended for 81000 users
recommended for 81500 users
recommended for 82000 users
recommended for 82500 users
recommended for 83000 users
recommended for 83500 users
recommended for 84000 users
recommended for 84500 users
recommended for 85000 users
recommended for 85500 users
recommended for 86000 users
recommended for 86500 users
recommended for 87000 users
recommended for 87500 users
recommended for 88000 users
recommended for 88500 users
recommended for 89000 users
recommended for 89500 users
recommended for 90000 users
recommended for 90500 users
recommended for 91000 users
recommended for 91500 users
recommended for 92000 users
recommended for 92500 users
recommended for 93000 users
recommended for 93500 users
recommended for 94000 users
recommended for 94500 users
recommended for 95000 users
recommended for 95500 users
recommended for 96000 users
recommended for 96500 users
recommended for 97000 users
recommended for 97500 users
recommended for 98000 users
recommended for 98500 users
recommended for 99000 users
recommended for 99500 users
recommended for 100000 users
recommended for 100500 users
recommended for 101000 users
recommended for 101500 users
recommended for 102000 users
recommended for 102500 users
recommended for 103000 users
recommended for 103500 users
recommended for 104000 users
recommended for 104500 users
Predict end...

,item_id,rec_users,rec_items,len
0,189045,"[(2158892, 3.6742346141747677), (220694, 0.408...","[2158892, 220694]",2
1,10713670,"[(102979, 5.242640687119285), (1081430, 1.4142...","[102979, 1081430, 1322529, 471295]",4
2,10546322,"[(1387152, 0.9428090415820635), (1709510, 0.70...","[1387152, 1709510, 1853302]",3
3,5199603,"[(103277, 2.0), (895432, 2.0), (404616, 1.0)]","[103277, 895432, 404616]",3
4,2477273,"[(1727071, 1.924500897298753)]",[1727071],1
5,2713102,"[(1969402, 1.2909944487358054), (1338701, 0.77...","[1969402, 1338701, 2144512, 103277]",4
6,8430088,"[(103277, 7.016507857945052), (1352544, 0.7071...","[103277, 1352544, 826684, 1129329, 1992851, 51...",16
7,9156316,"[(1716889, 3.681980515339464), (1957158, 2.176...","[1716889, 1957158, 263529, 1598310, 233273, 12...",11
8,3477402,"[(1376989, 4.76404691226986), (1710118, 0.7071...","[1376989, 1710118, 1366491, 1902807, 1576654, ...",30
9,4547408,"[(1745624, 7.0710678118654755)]",[1745624],1
10,10216832,"[(794452, 4.949747468305832), (1280264, 2.1213...","[794452, 1280264]",2
11,1602839,"[(104145, 10.0)]",[104145],1
12,7412985,"[(850637, 10.0)]",[850637],1
13,7451242,"[(850637, 10.0)]",[850637],1
14,6383803,"[(1920816, 5.0)]",[1920816],1
15,6550085,"[(269542, 7.0710678118654755)]",[269542],1
16,8192508,"[(850637, 10.0)]",[850637],1
17,11460802,"[(850637, 10.0)]",[850637],1
18,5278123,"[(850637, 10.0)]",[850637],1
19,8548120,"[(850637, 10.0)]",[850637],1
20,8099239,"[(1657125, 0.9922778767136676), (1673423, 0.31...","[1657125, 1673423, 355820, 2165648, 497280]",5
21,7521360,"[(1607755, 1.0832698208153353), (1463503, 0.58...","[1607755, 1463503, 733164, 1012527, 1318481, 1...",16
22,4685262,"[(1318168, 4.742640687119285), (2302927, 1.822...","[1318168, 2302927, 362160, 1931289, 875519]",5
23,1610811,"[(1782312, 7.0710678118654755)]",[1782312],1
24,4159513,"[(1152117, 4.912602954540573), (182819, 0.7071...","[1152117, 182819, 1690627, 1782312, 130062, 18...",30
25,5973981,"[(612211, 1.4596008983995232), (1534941, 0.417...","[612211, 1534941, 1258530]",3
26,9630517,"[(295483, 3.36504396942433), (1480942, 1.15470...","[295483, 1480942, 914978, 1043524, 12216022, 7...",8
27,6423473,"[(1918068, 1.2510864843424485), (1012784, 0.41...","[1918068, 1012784, 938608, 805035]",4
28,3060461,"[(1944372, 7.69023444431199), (1449933, 0.7071...","[1944372, 1449933, 955014, 161657, 1456681, 46...",10
29,10174763,"[(1944372, 1.5118578920369088), (1487378, 1.51...","[1944372, 1487378, 779836]",3
...,...,...,...,...
104705,9410651,"[(269542, 10.0)]",[269542],1
104706,5420789,"[(818384, 4.340228805803327), (962939, 0.51726...","[818384, 962939, 2089342, 1899307, 1993612, 73...",28
104707,6164695,"[(151627, 3.7796447300922726)]",[151627],1
104708,9745668,"[(1899705, 1.2649110640673518), (441234, 1.264...","[1899705, 441234, 1323111]",3
104709,8132205,"[(341192, 2.1213203435596424), (1881037, 1.414...","[341192, 1881037]",2
104710,3980451,"[(1926724, 10.0)]",[1926724],1
104711,11612688,"[(1243416, 3.832252782877816), (1273136, 0.577...","[1243416, 1273136, 742548, 1753724, 495950, 27...",30
104712,11764488,"[(1273136, 2.3094010767585034), (1243416, 1.73...","[1273136, 1243416, 742548, 12633780]",4
104713,9514838,"[(1243416, 3.832252782877816), (1273136, 0.577...","[1243416, 1273136, 742548, 1753724, 495950, 27...",30
104714,3168640,"[(1645611, 2.1828206253269973), (1120575, 0.24...","[1645611, 1120575]",2
104715,623407,"[(1243416, 3.832252782877816), (1273136, 0.577...","[1243416, 1273136, 742548, 1753724, 495950, 27...",30
104716,9268570,"[(681959, 1.7320508075688776), (1040387, 0.192...","[681959, 1040387]",2
104717,8931543,"[(1753724, 4.024922359499621), (271099, 0.4472...","[1753724, 271099]",2
104718,3208954,"[(1048308, 9.707106781186548), (2397317, 0.707...","[1048308, 2397317]",2
104719,2543998,"[(133490, 3.0295686340235055), (224893, 2.5236...","[133490, 224893, 109116, 625395, 676463, 68958...",11
104720,2742278,"[(625395, 2.822461852836958), (224893, 2.52360...","[625395, 224893, 2242464, 579907, 676463, 1334...",12
104721,12478258,"[(1043442, 1.2909944487358054), (1293139, 1.29...","[1043442, 1293139]",2
104722,12037837,"[(716821, 2.4494897427831783), (2150916, 1.224...","[716821, 2150916, 1931838]",3
104723,704840,"[(1690087, 2.886751345948129), (1814615, 2.309...","[1690087, 1814615, 2150916]",3
104724,6513863,"[(2150916, 3.7718113231265793), (1814615, 0.57...","[2150916, 1814615, 1690087, 1407268, 948886, 1...",19
104725,5378739,"[(1999509, 3.4016802570830453), (2021511, 0.37...","[1999509, 2021511]",2
104726,6704682,"[(2150916, 3.7718113231265793), (1814615, 0.57...","[2150916, 1814615, 1690087, 1407268, 948886, 1...",19
104727,4287248,"[(2150916, 3.7718113231265793), (1814615, 0.57...","[2150916, 1814615, 1690087, 1407268, 948886, 1...",19
104728,6520267,"[(2034780, 5.949747468305832), (1965049, 0.707...","[2034780, 1965049, 2269394, 912004]",4
104729,5832031,"[(137214, 5.949747468305832), (965111, 0.70710...","[137214, 965111, 67667, 2183494]",4
104730,10957153,"[(481075, 10.0)]",[481075],1
104731,4341301,"[(2203722, 5.773502691896259)]",[2203722],1
104732,422053,"[(1048308, 3.4016802570830453), (816302, 0.377...","[1048308, 816302]",2
104733,3690841,"[(1048308, 9.707106781186548), (2397317, 0.707...","[1048308, 2397317]",2
104734,3751035,"[(1364389, 5.707106781186548), (819758, 0.7071...","[1364389, 819758]",2

In [46]:
import sys
import random
import math
import os
from operator import itemgetter

from collections import defaultdict

random.seed(0)

class UserBasedCF(object):
    ''' TopN recommendation - User Based Collaborative Filtering '''

    # 构造函数，用来初始化
    def __init__(self):
        # 定义 训练集 测试集 为字典类型
        self.trainset = {}
        self.testset = {}
        # 训练集用的相似用户数
        self.n_sim_user = 10
        # 推荐Item数量
        self.n_rec_item = 30

        self.user_sim_mat = {}
        self.item_popular = {}
        self.item_count = 0
        # sys.stderr 是用来重定向标准错误信息的
        print ('相似用户数目为  %d' % self.n_sim_user, file=sys.stderr)
        print ('推荐Item数目为  %d' %
               self.n_rec_item, file=sys.stderr)

    # 划分训练集和测试集 pivot用来定义训练集和测试集的比例
    def generate_dataset(self, train, test=None, pivot=1):
        ''' load rating data and split it to training set and test set '''
        trainset_len = 0
        testset_len = 0
        if test is None:# 随机分配验证机实验 
            print('算法尝试！')
            for line in train.iterrows():
                user, item, rating = line[1][0],line[1][1],1
                # split the data by pivot
                if random.random() < pivot:
                    self.trainset.setdefault(user, {})
                    self.trainset[user][item] = int(rating)
                    trainset_len += 1
                else:
                    self.testset.setdefault(user, {})
                    self.testset[user][item] = int(rating)
                    testset_len += 1
        else:#真正预测
            print('预测尝试！')
            for line in train.iterrows():
                user, item, rating = line[1][0],line[1][1],1
                # split the data by pivot
                self.trainset.setdefault(user, {})
                self.trainset[user][item] = int(rating)
                trainset_len += 1
            del user,item,rating
            for line in test.iterrows():
                user, item, rating = line[1][0],line[1][1],1
                self.testset.setdefault(user, {})
                self.testset[user][item] = int(rating)
                testset_len += 1
        print ('split training set and test set succ')
        print ('train set = %s' % trainset_len)
        print ('test set = %s' % testset_len)
        
    # 建立物品-用户 倒排表
    def calc_user_sim(self):
        ''' calculate user similarity matrix '''
        # build inverse table for item-users
        # key=itemID, value=list of userIDs who have seen this item
        print ('构建物品-用户倒排表中，请等待......')
        item2users = dict()

        for user, items in self.trainset.items():
            for item in items:
                # inverse table for item-users
                if item not in item2users:
                    # 根据商品id 构造set() 函数创建一个无序不重复元素集
                    item2users[item] = set()
                item2users[item].add(user)
                # 记录电影的流行度
                if item not in self.item_popular:
                    self.item_popular[item] = 0
                self.item_popular[item] += 1
        print ('构建物品-用户倒排表成功', file=sys.stderr)

        # save the total item number, which will be used in evaluation
        self.item_count = len(item2users)
        print ('总共被操作过的物品数目为  %d' % self.item_count, file=sys.stderr)

        # count co-rated items between users
        usersim_mat = self.user_sim_mat

        print ('building user co-rated items matrix...', file=sys.stderr)
        # 令系数矩阵 C[u][v]表示N(u)∩N（v) ，假如用户u和用户v同时属于K个物品对应的用户列表，就有C[u][v]=K
        for item, users in item2users.items():
            for u in users:
                usersim_mat.setdefault(u, defaultdict(int))
                for v in users:
                    if u == v:
                        continue
                    usersim_mat[u][v] += 1
        print ('build user co-rated items matrix succ', file=sys.stderr)

        # calculate similarity matrix
        print ('calculating user similarity matrix...', file=sys.stderr)
        simfactor_count = 0
        PRINT_STEP = 2000000
        # 循环遍历usersim_mat 根据余弦相似度公式计算出用户兴趣相似度
        for u, related_users in usersim_mat.items():
            for v, count in related_users.items():
                # 以下是公式计算过程
                usersim_mat[u][v] = count / math.sqrt(
                    len(self.trainset[u]) * len(self.trainset[v]))
                #计数 并没有什么卵用
                simfactor_count += 1
                if simfactor_count % PRINT_STEP == 0:
                    print ('calculating user similarity factor(%d)' %
                           simfactor_count, file=sys.stderr)

        print ('calculate user similarity matrix(similarity factor) succ',
               file=sys.stderr)
        print ('Total similarity factor number = %d' %
               simfactor_count, file=sys.stderr)
        
    # 根据用户给予推荐结果
    def recommend(self, user, predict=False):
        '''定义给定K个相似用户和推荐N个商品'''
        K = self.n_sim_user
        N = self.n_rec_item
        # 定义一个字典来存储为用户推荐的电影
        rank = dict()
        
        watched_items = self.trainset[user]
        # sorted() 函数对所有可迭代的对象进行排序操作。 key 指定比较的对象 ，reverse=True 降序
        for similar_user, similarity_factor in sorted(self.user_sim_mat[user].items(),
                                                      key=itemgetter(1), reverse=True)[0:K]:
            for item in self.trainset[similar_user]:
                rank.setdefault(item, 0)
                rank[item] += similarity_factor
        # return the N best items
        return sorted(rank.items(), key=itemgetter(1), reverse=True)[0:N]
    
    def predict(self):
        print('Predict start...')

        N = self.n_rec_item
        #  varables for precision and recall
        hit = 0
        rec_count = 0
        test_count = 0
        # varables for coverage
        all_rec_items = set()
        # varables for popularity
        popular_sum = 0
        predict_result=[]
        for i, user in enumerate(self.testset):
            if i % 500 == 0:
                print ('recommended for %d users' % i)
            rec_items = self.recommend(user,predict=True)
            predict_result.append((user,rec_items))
        print('Predict end...')
        return predict_result
    
    # 计算 准确略，召回率，覆盖率，流行度
    def evaluate(self):
        ''' print evaluation result: precision, recall, coverage and popularity '''
        print ('Evaluation start...', file=sys.stderr)

        N = self.n_rec_item
        #  varables for precision and recall
        #记录推荐正确的item数
        hit = 0
        #记录推荐item的总数
        rec_count = 0
        #记录测试数据中总数
        test_count = 0
        # varables for coverage
        all_rec_items = set()
        # varables for popularity
        popular_sum = 0

        for i, user in enumerate(self.trainset):
            if i % 500 == 0:
                print ('recommended for %d users' % i, file=sys.stderr)
            test_items = self.testset.get(user, {})
            rec_items = self.recommend(user,predict=False)
            for item, _ in rec_items:
                if item in test_items:
                    hit += 1
                all_rec_items.add(item)
                popular_sum += math.log(1 + self.item_popular[item])
            rec_count += N
            test_count += len(test_items)
        # 计算准确度
        precision = hit / (1.0 * rec_count)
        # 计算召回率
        recall = hit / (1.0 * test_count)
        # 计算覆盖率
        coverage = len(all_rec_items) / (1.0 * self.item_count)
        #计算流行度
        popularity = popular_sum / (1.0 * rec_count)

        print ('precision=%.4f\trecall=%.4f\tcoverage=%.4f\tpopularity=%.4f' %
               (precision, recall, coverage, popularity), file=sys.stderr)